# Few-shot dataset
nClsEpisode: 5 # number of categories in each episode
nSupport: 1 # number of samples per category in the support set
nQuery: 15 # number of samples per category in the query set
dataset: 'miniImageNet' # choices = ['miniImageNet', 'Cifar']

# Network
nStep: 3 # number of synthetic gradient steps
architecture: 'WRN_28_10'  # choices = ['WRN_28_10', 'Conv64_4']
batchSize: 8 # number of episodes in each batch

# Optimizer
lr: 0.001 # lr is fixed
weightDecay: 0.0005 
momentum: 0.9 

# Training details
expName: miniImageNet
nbIter: 50000 # number of training iterations
seed: 100 # can be reset with --seed
gpu: '1' # can be reset with --gpu
resumeFeatPth: './ckpts/Mini-ImageNet/netFeatBest64.653.pth'
ckptPth: '' # model ckpt for finetuning
#ckptPth: 'cache/miniImageNet_1shot_100/outputs_73.924/netSIBBest73.924.pth'
coeffGrad: 0 # grad loss coeff

# Testing
nEpisode: 2000 # number of episodes for testing
